project:
  type: website
  output-dir : docs

website:
  title: "Crop_yield_CW"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 100-eda.qmd
      - 200-model-fit.qmd
      - 300-forecast.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

